services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_river_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  river-ui:
    image: ghcr.io/riverqueue/riverui:latest
    container_name: river_ui
    restart: always
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable"
    depends_on:
      - postgres

volumes:
  pgdata:
