// Code generated by ent, DO NOT EDIT.

package movie

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the movie type in the database.
	Label = "movie"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldReleaseYear holds the string denoting the release_year field in the database.
	FieldReleaseYear = "release_year"
	// FieldQuality holds the string denoting the quality field in the database.
	FieldQuality = "quality"
	// EdgeCasts holds the string denoting the casts edge name in mutations.
	EdgeCasts = "casts"
	// Table holds the table name of the movie in the database.
	Table = "movies"
	// CastsTable is the table that holds the casts relation/edge. The primary key declared below.
	CastsTable = "movie_casts"
	// CastsInverseTable is the table name for the Cast entity.
	// It exists in this package in order to avoid circular dependency with the "cast" package.
	CastsInverseTable = "casts"
)

// Columns holds all SQL columns for movie fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldReleaseYear,
	FieldQuality,
}

var (
	// CastsPrimaryKey and CastsColumn2 are the table columns denoting the
	// primary key for the casts relation (M2M).
	CastsPrimaryKey = []string{"movie_id", "cast_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Quality defines the type for the "quality" enum field.
type Quality string

// Quality values.
const (
	Quality720p  Quality = "720p"
	Quality1080p Quality = "1080p"
	Quality4K    Quality = "4K"
)

func (q Quality) String() string {
	return string(q)
}

// QualityValidator is a validator for the "quality" field enum values. It is called by the builders before save.
func QualityValidator(q Quality) error {
	switch q {
	case Quality720p, Quality1080p, Quality4K:
		return nil
	default:
		return fmt.Errorf("movie: invalid enum value for quality field: %q", q)
	}
}

// OrderOption defines the ordering options for the Movie queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByReleaseYear orders the results by the release_year field.
func ByReleaseYear(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReleaseYear, opts...).ToFunc()
}

// ByQuality orders the results by the quality field.
func ByQuality(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuality, opts...).ToFunc()
}

// ByCastsCount orders the results by casts count.
func ByCastsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCastsStep(), opts...)
	}
}

// ByCasts orders the results by casts terms.
func ByCasts(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCastsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newCastsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CastsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, CastsTable, CastsPrimaryKey...),
	)
}
