[request_definition]
r = ip, program, location, direction

[policy_definition] # rule
p = ip_role, program, location, direction, eft

[role_definition] # role
g = _, _

[policy_effect]
e = some(where (p.eft == allow)) && !some(where (p.eft == deny))

[matchers]
m = g(r.ip, p.ip_role) && p.program == r.program && p.location == r.location && p.direction == r.direction

# r , p , g , e , m , [...] , eft are Keywords!!!!!!!!!!!