// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Cast is the predicate function for cast builders.
type Cast func(*sql.Selector)

// Movie is the predicate function for movie builders.
type Movie func(*sql.Selector)
