// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"ent-demo/ent/cast"
	"ent-demo/ent/movie"
	"ent-demo/ent/predicate"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CastUpdate is the builder for updating Cast entities.
type CastUpdate struct {
	config
	hooks    []Hook
	mutation *CastMutation
}

// Where appends a list predicates to the CastUpdate builder.
func (_u *CastUpdate) Where(ps ...predicate.Cast) *CastUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *CastUpdate) SetName(v string) *CastUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CastUpdate) SetNillableName(v *string) *CastUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// AddMovieIDs adds the "movies" edge to the Movie entity by IDs.
func (_u *CastUpdate) AddMovieIDs(ids ...int) *CastUpdate {
	_u.mutation.AddMovieIDs(ids...)
	return _u
}

// AddMovies adds the "movies" edges to the Movie entity.
func (_u *CastUpdate) AddMovies(v ...*Movie) *CastUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMovieIDs(ids...)
}

// Mutation returns the CastMutation object of the builder.
func (_u *CastUpdate) Mutation() *CastMutation {
	return _u.mutation
}

// ClearMovies clears all "movies" edges to the Movie entity.
func (_u *CastUpdate) ClearMovies() *CastUpdate {
	_u.mutation.ClearMovies()
	return _u
}

// RemoveMovieIDs removes the "movies" edge to Movie entities by IDs.
func (_u *CastUpdate) RemoveMovieIDs(ids ...int) *CastUpdate {
	_u.mutation.RemoveMovieIDs(ids...)
	return _u
}

// RemoveMovies removes "movies" edges to Movie entities.
func (_u *CastUpdate) RemoveMovies(v ...*Movie) *CastUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMovieIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CastUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CastUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CastUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CastUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *CastUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(cast.Table, cast.Columns, sqlgraph.NewFieldSpec(cast.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(cast.FieldName, field.TypeString, value)
	}
	if _u.mutation.MoviesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   cast.MoviesTable,
			Columns: cast.MoviesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(movie.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMoviesIDs(); len(nodes) > 0 && !_u.mutation.MoviesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   cast.MoviesTable,
			Columns: cast.MoviesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(movie.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MoviesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   cast.MoviesTable,
			Columns: cast.MoviesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(movie.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cast.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CastUpdateOne is the builder for updating a single Cast entity.
type CastUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CastMutation
}

// SetName sets the "name" field.
func (_u *CastUpdateOne) SetName(v string) *CastUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CastUpdateOne) SetNillableName(v *string) *CastUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// AddMovieIDs adds the "movies" edge to the Movie entity by IDs.
func (_u *CastUpdateOne) AddMovieIDs(ids ...int) *CastUpdateOne {
	_u.mutation.AddMovieIDs(ids...)
	return _u
}

// AddMovies adds the "movies" edges to the Movie entity.
func (_u *CastUpdateOne) AddMovies(v ...*Movie) *CastUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMovieIDs(ids...)
}

// Mutation returns the CastMutation object of the builder.
func (_u *CastUpdateOne) Mutation() *CastMutation {
	return _u.mutation
}

// ClearMovies clears all "movies" edges to the Movie entity.
func (_u *CastUpdateOne) ClearMovies() *CastUpdateOne {
	_u.mutation.ClearMovies()
	return _u
}

// RemoveMovieIDs removes the "movies" edge to Movie entities by IDs.
func (_u *CastUpdateOne) RemoveMovieIDs(ids ...int) *CastUpdateOne {
	_u.mutation.RemoveMovieIDs(ids...)
	return _u
}

// RemoveMovies removes "movies" edges to Movie entities.
func (_u *CastUpdateOne) RemoveMovies(v ...*Movie) *CastUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMovieIDs(ids...)
}

// Where appends a list predicates to the CastUpdate builder.
func (_u *CastUpdateOne) Where(ps ...predicate.Cast) *CastUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CastUpdateOne) Select(field string, fields ...string) *CastUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Cast entity.
func (_u *CastUpdateOne) Save(ctx context.Context) (*Cast, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CastUpdateOne) SaveX(ctx context.Context) *Cast {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CastUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CastUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *CastUpdateOne) sqlSave(ctx context.Context) (_node *Cast, err error) {
	_spec := sqlgraph.NewUpdateSpec(cast.Table, cast.Columns, sqlgraph.NewFieldSpec(cast.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Cast.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cast.FieldID)
		for _, f := range fields {
			if !cast.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != cast.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(cast.FieldName, field.TypeString, value)
	}
	if _u.mutation.MoviesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   cast.MoviesTable,
			Columns: cast.MoviesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(movie.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMoviesIDs(); len(nodes) > 0 && !_u.mutation.MoviesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   cast.MoviesTable,
			Columns: cast.MoviesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(movie.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MoviesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   cast.MoviesTable,
			Columns: cast.MoviesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(movie.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Cast{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cast.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
