// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ent-demo/ent/movie"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Movie is the model entity for the Movie schema.
type Movie struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// ReleaseYear holds the value of the "release_year" field.
	ReleaseYear int `json:"release_year,omitempty"`
	// Quality holds the value of the "quality" field.
	Quality movie.Quality `json:"quality,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MovieQuery when eager-loading is set.
	Edges        MovieEdges `json:"edges"`
	selectValues sql.SelectValues
}

// MovieEdges holds the relations/edges for other nodes in the graph.
type MovieEdges struct {
	// Casts holds the value of the casts edge.
	Casts []*Cast `json:"casts,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// CastsOrErr returns the Casts value or an error if the edge
// was not loaded in eager-loading.
func (e MovieEdges) CastsOrErr() ([]*Cast, error) {
	if e.loadedTypes[0] {
		return e.Casts, nil
	}
	return nil, &NotLoadedError{edge: "casts"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Movie) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case movie.FieldID, movie.FieldReleaseYear:
			values[i] = new(sql.NullInt64)
		case movie.FieldTitle, movie.FieldQuality:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Movie fields.
func (_m *Movie) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case movie.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case movie.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case movie.FieldReleaseYear:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field release_year", values[i])
			} else if value.Valid {
				_m.ReleaseYear = int(value.Int64)
			}
		case movie.FieldQuality:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field quality", values[i])
			} else if value.Valid {
				_m.Quality = movie.Quality(value.String)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Movie.
// This includes values selected through modifiers, order, etc.
func (_m *Movie) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCasts queries the "casts" edge of the Movie entity.
func (_m *Movie) QueryCasts() *CastQuery {
	return NewMovieClient(_m.config).QueryCasts(_m)
}

// Update returns a builder for updating this Movie.
// Note that you need to call Movie.Unwrap() before calling this method if this Movie
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Movie) Update() *MovieUpdateOne {
	return NewMovieClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Movie entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Movie) Unwrap() *Movie {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Movie is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Movie) String() string {
	var builder strings.Builder
	builder.WriteString("Movie(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("release_year=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReleaseYear))
	builder.WriteString(", ")
	builder.WriteString("quality=")
	builder.WriteString(fmt.Sprintf("%v", _m.Quality))
	builder.WriteByte(')')
	return builder.String()
}

// Movies is a parsable slice of Movie.
type Movies []*Movie
