// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CastsColumns holds the columns for the "casts" table.
	CastsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
	}
	// CastsTable holds the schema information for the "casts" table.
	CastsTable = &schema.Table{
		Name:       "casts",
		Columns:    CastsColumns,
		PrimaryKey: []*schema.Column{CastsColumns[0]},
	}
	// MoviesColumns holds the columns for the "movies" table.
	MoviesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "release_year", Type: field.TypeInt},
		{Name: "quality", Type: field.TypeEnum, Enums: []string{"720p", "1080p", "4K"}},
	}
	// MoviesTable holds the schema information for the "movies" table.
	MoviesTable = &schema.Table{
		Name:       "movies",
		Columns:    MoviesColumns,
		PrimaryKey: []*schema.Column{MoviesColumns[0]},
	}
	// MovieCastsColumns holds the columns for the "movie_casts" table.
	MovieCastsColumns = []*schema.Column{
		{Name: "movie_id", Type: field.TypeInt},
		{Name: "cast_id", Type: field.TypeInt},
	}
	// MovieCastsTable holds the schema information for the "movie_casts" table.
	MovieCastsTable = &schema.Table{
		Name:       "movie_casts",
		Columns:    MovieCastsColumns,
		PrimaryKey: []*schema.Column{MovieCastsColumns[0], MovieCastsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "movie_casts_movie_id",
				Columns:    []*schema.Column{MovieCastsColumns[0]},
				RefColumns: []*schema.Column{MoviesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "movie_casts_cast_id",
				Columns:    []*schema.Column{MovieCastsColumns[1]},
				RefColumns: []*schema.Column{CastsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CastsTable,
		MoviesTable,
		MovieCastsTable,
	}
)

func init() {
	MovieCastsTable.ForeignKeys[0].RefTable = MoviesTable
	MovieCastsTable.ForeignKeys[1].RefTable = CastsTable
}
