// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ent-demo/ent/cast"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Cast is the model entity for the Cast schema.
type Cast struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CastQuery when eager-loading is set.
	Edges        CastEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CastEdges holds the relations/edges for other nodes in the graph.
type CastEdges struct {
	// Movies holds the value of the movies edge.
	Movies []*Movie `json:"movies,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// MoviesOrErr returns the Movies value or an error if the edge
// was not loaded in eager-loading.
func (e CastEdges) MoviesOrErr() ([]*Movie, error) {
	if e.loadedTypes[0] {
		return e.Movies, nil
	}
	return nil, &NotLoadedError{edge: "movies"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Cast) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case cast.FieldID:
			values[i] = new(sql.NullInt64)
		case cast.FieldName:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Cast fields.
func (_m *Cast) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case cast.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case cast.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Cast.
// This includes values selected through modifiers, order, etc.
func (_m *Cast) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMovies queries the "movies" edge of the Cast entity.
func (_m *Cast) QueryMovies() *MovieQuery {
	return NewCastClient(_m.config).QueryMovies(_m)
}

// Update returns a builder for updating this Cast.
// Note that you need to call Cast.Unwrap() before calling this method if this Cast
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Cast) Update() *CastUpdateOne {
	return NewCastClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Cast entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Cast) Unwrap() *Cast {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Cast is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Cast) String() string {
	var builder strings.Builder
	builder.WriteString("Cast(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteByte(')')
	return builder.String()
}

// Casts is a parsable slice of Cast.
type Casts []*Cast
