// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"ent-demo/ent/cast"
	"ent-demo/ent/movie"
	"ent-demo/ent/predicate"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MovieUpdate is the builder for updating Movie entities.
type MovieUpdate struct {
	config
	hooks    []Hook
	mutation *MovieMutation
}

// Where appends a list predicates to the MovieUpdate builder.
func (_u *MovieUpdate) Where(ps ...predicate.Movie) *MovieUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *MovieUpdate) SetTitle(v string) *MovieUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *MovieUpdate) SetNillableTitle(v *string) *MovieUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetReleaseYear sets the "release_year" field.
func (_u *MovieUpdate) SetReleaseYear(v int) *MovieUpdate {
	_u.mutation.ResetReleaseYear()
	_u.mutation.SetReleaseYear(v)
	return _u
}

// SetNillableReleaseYear sets the "release_year" field if the given value is not nil.
func (_u *MovieUpdate) SetNillableReleaseYear(v *int) *MovieUpdate {
	if v != nil {
		_u.SetReleaseYear(*v)
	}
	return _u
}

// AddReleaseYear adds value to the "release_year" field.
func (_u *MovieUpdate) AddReleaseYear(v int) *MovieUpdate {
	_u.mutation.AddReleaseYear(v)
	return _u
}

// SetQuality sets the "quality" field.
func (_u *MovieUpdate) SetQuality(v movie.Quality) *MovieUpdate {
	_u.mutation.SetQuality(v)
	return _u
}

// SetNillableQuality sets the "quality" field if the given value is not nil.
func (_u *MovieUpdate) SetNillableQuality(v *movie.Quality) *MovieUpdate {
	if v != nil {
		_u.SetQuality(*v)
	}
	return _u
}

// AddCastIDs adds the "casts" edge to the Cast entity by IDs.
func (_u *MovieUpdate) AddCastIDs(ids ...int) *MovieUpdate {
	_u.mutation.AddCastIDs(ids...)
	return _u
}

// AddCasts adds the "casts" edges to the Cast entity.
func (_u *MovieUpdate) AddCasts(v ...*Cast) *MovieUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCastIDs(ids...)
}

// Mutation returns the MovieMutation object of the builder.
func (_u *MovieUpdate) Mutation() *MovieMutation {
	return _u.mutation
}

// ClearCasts clears all "casts" edges to the Cast entity.
func (_u *MovieUpdate) ClearCasts() *MovieUpdate {
	_u.mutation.ClearCasts()
	return _u
}

// RemoveCastIDs removes the "casts" edge to Cast entities by IDs.
func (_u *MovieUpdate) RemoveCastIDs(ids ...int) *MovieUpdate {
	_u.mutation.RemoveCastIDs(ids...)
	return _u
}

// RemoveCasts removes "casts" edges to Cast entities.
func (_u *MovieUpdate) RemoveCasts(v ...*Cast) *MovieUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCastIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MovieUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MovieUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MovieUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MovieUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MovieUpdate) check() error {
	if v, ok := _u.mutation.Quality(); ok {
		if err := movie.QualityValidator(v); err != nil {
			return &ValidationError{Name: "quality", err: fmt.Errorf(`ent: validator failed for field "Movie.quality": %w`, err)}
		}
	}
	return nil
}

func (_u *MovieUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(movie.Table, movie.Columns, sqlgraph.NewFieldSpec(movie.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(movie.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReleaseYear(); ok {
		_spec.SetField(movie.FieldReleaseYear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReleaseYear(); ok {
		_spec.AddField(movie.FieldReleaseYear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Quality(); ok {
		_spec.SetField(movie.FieldQuality, field.TypeEnum, value)
	}
	if _u.mutation.CastsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   movie.CastsTable,
			Columns: movie.CastsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cast.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCastsIDs(); len(nodes) > 0 && !_u.mutation.CastsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   movie.CastsTable,
			Columns: movie.CastsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cast.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CastsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   movie.CastsTable,
			Columns: movie.CastsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cast.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{movie.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MovieUpdateOne is the builder for updating a single Movie entity.
type MovieUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MovieMutation
}

// SetTitle sets the "title" field.
func (_u *MovieUpdateOne) SetTitle(v string) *MovieUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *MovieUpdateOne) SetNillableTitle(v *string) *MovieUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetReleaseYear sets the "release_year" field.
func (_u *MovieUpdateOne) SetReleaseYear(v int) *MovieUpdateOne {
	_u.mutation.ResetReleaseYear()
	_u.mutation.SetReleaseYear(v)
	return _u
}

// SetNillableReleaseYear sets the "release_year" field if the given value is not nil.
func (_u *MovieUpdateOne) SetNillableReleaseYear(v *int) *MovieUpdateOne {
	if v != nil {
		_u.SetReleaseYear(*v)
	}
	return _u
}

// AddReleaseYear adds value to the "release_year" field.
func (_u *MovieUpdateOne) AddReleaseYear(v int) *MovieUpdateOne {
	_u.mutation.AddReleaseYear(v)
	return _u
}

// SetQuality sets the "quality" field.
func (_u *MovieUpdateOne) SetQuality(v movie.Quality) *MovieUpdateOne {
	_u.mutation.SetQuality(v)
	return _u
}

// SetNillableQuality sets the "quality" field if the given value is not nil.
func (_u *MovieUpdateOne) SetNillableQuality(v *movie.Quality) *MovieUpdateOne {
	if v != nil {
		_u.SetQuality(*v)
	}
	return _u
}

// AddCastIDs adds the "casts" edge to the Cast entity by IDs.
func (_u *MovieUpdateOne) AddCastIDs(ids ...int) *MovieUpdateOne {
	_u.mutation.AddCastIDs(ids...)
	return _u
}

// AddCasts adds the "casts" edges to the Cast entity.
func (_u *MovieUpdateOne) AddCasts(v ...*Cast) *MovieUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCastIDs(ids...)
}

// Mutation returns the MovieMutation object of the builder.
func (_u *MovieUpdateOne) Mutation() *MovieMutation {
	return _u.mutation
}

// ClearCasts clears all "casts" edges to the Cast entity.
func (_u *MovieUpdateOne) ClearCasts() *MovieUpdateOne {
	_u.mutation.ClearCasts()
	return _u
}

// RemoveCastIDs removes the "casts" edge to Cast entities by IDs.
func (_u *MovieUpdateOne) RemoveCastIDs(ids ...int) *MovieUpdateOne {
	_u.mutation.RemoveCastIDs(ids...)
	return _u
}

// RemoveCasts removes "casts" edges to Cast entities.
func (_u *MovieUpdateOne) RemoveCasts(v ...*Cast) *MovieUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCastIDs(ids...)
}

// Where appends a list predicates to the MovieUpdate builder.
func (_u *MovieUpdateOne) Where(ps ...predicate.Movie) *MovieUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MovieUpdateOne) Select(field string, fields ...string) *MovieUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Movie entity.
func (_u *MovieUpdateOne) Save(ctx context.Context) (*Movie, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MovieUpdateOne) SaveX(ctx context.Context) *Movie {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MovieUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MovieUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MovieUpdateOne) check() error {
	if v, ok := _u.mutation.Quality(); ok {
		if err := movie.QualityValidator(v); err != nil {
			return &ValidationError{Name: "quality", err: fmt.Errorf(`ent: validator failed for field "Movie.quality": %w`, err)}
		}
	}
	return nil
}

func (_u *MovieUpdateOne) sqlSave(ctx context.Context) (_node *Movie, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(movie.Table, movie.Columns, sqlgraph.NewFieldSpec(movie.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Movie.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, movie.FieldID)
		for _, f := range fields {
			if !movie.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != movie.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(movie.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReleaseYear(); ok {
		_spec.SetField(movie.FieldReleaseYear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReleaseYear(); ok {
		_spec.AddField(movie.FieldReleaseYear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Quality(); ok {
		_spec.SetField(movie.FieldQuality, field.TypeEnum, value)
	}
	if _u.mutation.CastsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   movie.CastsTable,
			Columns: movie.CastsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cast.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCastsIDs(); len(nodes) > 0 && !_u.mutation.CastsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   movie.CastsTable,
			Columns: movie.CastsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cast.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CastsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   movie.CastsTable,
			Columns: movie.CastsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cast.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Movie{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{movie.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
