// Code generated by ent, DO NOT EDIT.

package movie

import (
	"ent-demo/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Movie {
	return predicate.Movie(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Movie {
	return predicate.Movie(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Movie {
	return predicate.Movie(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Movie {
	return predicate.Movie(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Movie {
	return predicate.Movie(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Movie {
	return predicate.Movie(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Movie {
	return predicate.Movie(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Movie {
	return predicate.Movie(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Movie {
	return predicate.Movie(sql.FieldLTE(FieldID, id))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Movie {
	return predicate.Movie(sql.FieldEQ(FieldTitle, v))
}

// ReleaseYear applies equality check predicate on the "release_year" field. It's identical to ReleaseYearEQ.
func ReleaseYear(v int) predicate.Movie {
	return predicate.Movie(sql.FieldEQ(FieldReleaseYear, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Movie {
	return predicate.Movie(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Movie {
	return predicate.Movie(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Movie {
	return predicate.Movie(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Movie {
	return predicate.Movie(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Movie {
	return predicate.Movie(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Movie {
	return predicate.Movie(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Movie {
	return predicate.Movie(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Movie {
	return predicate.Movie(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Movie {
	return predicate.Movie(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Movie {
	return predicate.Movie(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Movie {
	return predicate.Movie(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Movie {
	return predicate.Movie(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Movie {
	return predicate.Movie(sql.FieldContainsFold(FieldTitle, v))
}

// ReleaseYearEQ applies the EQ predicate on the "release_year" field.
func ReleaseYearEQ(v int) predicate.Movie {
	return predicate.Movie(sql.FieldEQ(FieldReleaseYear, v))
}

// ReleaseYearNEQ applies the NEQ predicate on the "release_year" field.
func ReleaseYearNEQ(v int) predicate.Movie {
	return predicate.Movie(sql.FieldNEQ(FieldReleaseYear, v))
}

// ReleaseYearIn applies the In predicate on the "release_year" field.
func ReleaseYearIn(vs ...int) predicate.Movie {
	return predicate.Movie(sql.FieldIn(FieldReleaseYear, vs...))
}

// ReleaseYearNotIn applies the NotIn predicate on the "release_year" field.
func ReleaseYearNotIn(vs ...int) predicate.Movie {
	return predicate.Movie(sql.FieldNotIn(FieldReleaseYear, vs...))
}

// ReleaseYearGT applies the GT predicate on the "release_year" field.
func ReleaseYearGT(v int) predicate.Movie {
	return predicate.Movie(sql.FieldGT(FieldReleaseYear, v))
}

// ReleaseYearGTE applies the GTE predicate on the "release_year" field.
func ReleaseYearGTE(v int) predicate.Movie {
	return predicate.Movie(sql.FieldGTE(FieldReleaseYear, v))
}

// ReleaseYearLT applies the LT predicate on the "release_year" field.
func ReleaseYearLT(v int) predicate.Movie {
	return predicate.Movie(sql.FieldLT(FieldReleaseYear, v))
}

// ReleaseYearLTE applies the LTE predicate on the "release_year" field.
func ReleaseYearLTE(v int) predicate.Movie {
	return predicate.Movie(sql.FieldLTE(FieldReleaseYear, v))
}

// QualityEQ applies the EQ predicate on the "quality" field.
func QualityEQ(v Quality) predicate.Movie {
	return predicate.Movie(sql.FieldEQ(FieldQuality, v))
}

// QualityNEQ applies the NEQ predicate on the "quality" field.
func QualityNEQ(v Quality) predicate.Movie {
	return predicate.Movie(sql.FieldNEQ(FieldQuality, v))
}

// QualityIn applies the In predicate on the "quality" field.
func QualityIn(vs ...Quality) predicate.Movie {
	return predicate.Movie(sql.FieldIn(FieldQuality, vs...))
}

// QualityNotIn applies the NotIn predicate on the "quality" field.
func QualityNotIn(vs ...Quality) predicate.Movie {
	return predicate.Movie(sql.FieldNotIn(FieldQuality, vs...))
}

// HasCasts applies the HasEdge predicate on the "casts" edge.
func HasCasts() predicate.Movie {
	return predicate.Movie(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, CastsTable, CastsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCastsWith applies the HasEdge predicate on the "casts" edge with a given conditions (other predicates).
func HasCastsWith(preds ...predicate.Cast) predicate.Movie {
	return predicate.Movie(func(s *sql.Selector) {
		step := newCastsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Movie) predicate.Movie {
	return predicate.Movie(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Movie) predicate.Movie {
	return predicate.Movie(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Movie) predicate.Movie {
	return predicate.Movie(sql.NotPredicates(p))
}
